services:
  api-solid-pg:
    image: postgres:16.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ignitenode03
    volumes:
      - ./data:/var/lib/postgresql/data